# Generated by Django 5.1.5 on 2025-01-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directormodel',
            name='foto',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='directormodel',
            name='experience',
            field=models.IntegerField(verbose_name='Опыт, количество лет'),
        ),
        migrations.AlterField(
            model_name='directormodel',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='directormodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя режиссера'),
        ),
        migrations.AlterField(
            model_name='directormodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Стоимость за смену'),
        ),
    ]
