# Generated by Django 5.1.5 on 2025-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectApp', '0002_directormodel_foto_alter_directormodel_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directormodel',
            name='foto',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
