# Generated by Django 5.1.5 on 2025-01-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelectApp', '0003_alter_directormodel_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directormodel',
            name='foto',
        ),
    ]
