# Generated by Django 5.1.5 on 2025-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelectApp', '0004_remove_directormodel_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='directormodel',
            name='foto',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
